### PR TITLE
Improve quote detection

### PR DESCRIPTION
**Pull request by evonck**
2 Update:

Correctly handle cases where the quotation mark is placed before some <div>. Some email are sending > <div> Text. The new version will first look for some quotation using the div as a line breaker. If no quotation it will try again considering the div as inline

Handle error when the node limit is crossed. When an email contains more than 1000 tags we used to stop parsing the tag and look for a quotation in the email using only 1000 tags. This resulted in mail where the quotation where being truncated. If the message has too many tag we will not parse it. Also add a isTooLong info on the parameter to know if the message has been filtered for quote.

### CODE REVIEW

**Comment by evonck** [comment]
@seanxiesx I don't have write access to the repe

**Comment by seanxiesx** [comment]
> @seanxiesx I don't have write access to the repe

done. works?

**Comment by evonck** [comment]
@seanxiesx nope Only those with write access to this repository can merge pull requests.

**Comment by seanxiesx** [comment]
hi @evonck 👋

**Pull request closed without merging**
